export const routes = {
    welcome: "/",
    home: "/home",
    farm: "/farm",
    createFarm:"/farm/create-farm",
    farmDetails: "/farm/:id",
    updateFarm: "/farm/:id/update-farm",
    field: "/field",
    createField: "/field/create-field",
    fieldDetails: "/field/:id",
    updateField: "/field/:id/update-field",
    machine: "/machine",
    createMachine: "/machine/create-machine",
    machineDetails: "/machine/:id",
    updateMachine:"/machine/:id/update-machine",
    crop: "/crop",
    soil: "/soil",
    processType: "/process-type",
    fieldCultivation:"/field-cultivation",
    notFound: "*",
  };
  